services:
  # We removed mongodb service so backend will fallback to using the Atlas MONGO_URI in backend/.env

  redis:
    image: redis:alpine
    container_name: ddtec-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ddtec-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ddtec-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - REDIS_URI=redis://redis:6379
    env_file:
      - ./backend/.env
    # depends_on:
    #  - mongodb
    depends_on:
      - redis
    networks:
      - ddtec-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
    container_name: ddtec-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - ddtec-network

# volumes:
#   mongo_data:
#     driver: local

networks:
  ddtec-network:
    driver: bridge
