export enum CompanyRole {
  OWNER = "OWNER",
  HR = "HR",
}

export enum StipendType {
  FIXED = "FIXED",
  PERFORMANCE_BASED = "PERFORMANCE_BASED",
  UNPAID = "UNPAID",
}

export enum DurationType {
  WEEKS = "WEEKS",
  MONTHS = "MONTHS",
}

export enum WorkMode {
  WORKFROMOFFICE = "WORK_FROM_OFFICE",
  REMOTE = "REMOTE",
  HYBRID = "HYBRID",
  TEMPWFH = "TEMPORARY_WFH",
}

export enum WorkType {
  REMOTE = "REMOTE",
  HYBRID = "HYBRID",
  ON_SITE = "ON_SITE",
}

export enum GlobalRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  USER = "USER",
}

export enum RoleCategory {
  SOFTWARE_DEVELOPMENT = "SOFTWARE_DEVELOPMENT",
  DATA_SCIENCE = "DATA_SCIENCE",
  DEVOPS = "DEVOPS",
  CYBERSECURITY = "CYBERSECURITY",
  IT_SUPPORT = "IT_SUPPORT",
  QA_TESTING = "QA_TESTING",
  HARDWARE = "HARDWARE",
  UI_UX = "UI_UX",
  GRAPHIC_DESIGN = "GRAPHIC_DESIGN",
  PRODUCT_DESIGN = "PRODUCT_DESIGN",
  PRODUCT_MANAGEMENT = "PRODUCT_MANAGEMENT",
  PROJECT_MANAGEMENT = "PROJECT_MANAGEMENT",
  BUSINESS_ANALYSIS = "BUSINESS_ANALYSIS",
  OPERATIONS = "OPERATIONS",
  CONSULTING = "CONSULTING",
  SALES = "SALES",
  DIGITAL_MARKETING = "DIGITAL_MARKETING",
  CONTENT = "CONTENT",
  SEO_SEM = "SEO_SEM",
  BRAND_MANAGEMENT = "BRAND_MANAGEMENT",
  FINANCE = "FINANCE",
  ACCOUNTING = "ACCOUNTING",
  LEGAL = "LEGAL",
  COMPLIANCE = "COMPLIANCE",
  HUMAN_RESOURCES = "HUMAN_RESOURCES",
  RECRUITMENT = "RECRUITMENT",
  ADMINISTRATION = "ADMINISTRATION",
  CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT",
  RESEARCH = "RESEARCH",
  OTHER = "OTHER",
}

export enum Industry {
  INFORMATION_TECHNOLOGY = "INFORMATION_TECHNOLOGY",
  SOFTWARE = "SOFTWARE",
  ECOMMERCE = "ECOMMERCE",
  FINTECH = "FINTECH",
  EDTECH = "EDTECH",
  HEALTHTECH = "HEALTHTECH",
  BANKING = "BANKING",
  INSURANCE = "INSURANCE",
  HEALTHCARE = "HEALTHCARE",
  EDUCATION = "EDUCATION",
  MANUFACTURING = "MANUFACTURING",
  RETAIL = "RETAIL",
  REAL_ESTATE = "REAL_ESTATE",
  LOGISTICS = "LOGISTICS",
  AUTOMOTIVE = "AUTOMOTIVE",
  ENERGY = "ENERGY",
  TELECOM = "TELECOM",
  MEDIA = "MEDIA",
  ENTERTAINMENT = "ENTERTAINMENT",
  HOSPITALITY = "HOSPITALITY",
  AGRICULTURE = "AGRICULTURE",
  GOVERNMENT = "GOVERNMENT",
  NONPROFIT = "NONPROFIT",
  OTHER = "OTHER",
}

export enum ListingType {
  JOB = "JOB",
  INTERNSHIP = "INTERNSHIP",
}

export enum PaymentMethod {
  CARD = "CARD",
  UPI = "UPI",
  NET_BANKING = "NETBANKING",
  WALLET = "WALLET",
}

export enum InternshipDurationType {
  WEEKS = "WEEKS",
  MONTHS = "MONTHS",
}

export enum KycStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum CouponType {
  PERCENTAGE = "PERCENTAGE",
  AMOUNT = "AMOUNT",
}

export enum CompanyType {
  STARTUP = "STARTUP",
  MNC = "MNC",
  FOREIGN_MNC = "FOREIGN_MNC",
  INDIAN_MNC = "INDIAN_MNC",
  CORPORATE = "CORPORATE",
  "GOVT/PSU" = "GOVT_PSU",
  OTHERS = "OTHERS",
}

export enum DegreeLevel {
  HIGH_SCHOOL = "HIGH_SCHOOL",
  DIPLOMA = "DIPLOMA",
  BACHELORS = "BACHELORS",
  MASTERS = "MASTERS",
  PHD = "PHD",
  ANY = "ANY",
}

export enum ApplicationStatus {
  PENDING = "PENDING",
  REVIEWED = "REVIEWED",
  SHORTLISTED = "SHORTLISTED",
  REJECTED = "REJECTED",
  INTERVIEW = "INTERVIEW",
  OFFERED = "OFFERED",
  ACCEPTED = "ACCEPTED",
  WITHDRAWN = "WITHDRAWN",
}

export enum SubscriptionStatus {
  ACTIVE = "ACTIVE",
  EXPIRED = "EXPIRED",
  DEPLETED = "DEPLETED",
  CANCELLED = "CANCELLED",
}

export enum ExperienceLevel {
  ENTRY = "ENTRY",
  INTERMEDIATE = "INTERMEDIATE",
  SENIOR = "SENIOR",
  EXPERT = "EXPERT",
}

export enum EmploymentType {
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  CONTRACT = "CONTRACT",
  INTERNSHIP = "INTERNSHIP",
  FREELANCE = "FREELANCE",
}

export enum PaymentStatus {
  CREATED = "CREATED",
  AUTHORIZED = "AUTHORIZED",
  CAPTURED = "CAPTURED",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum JobStatus {
  ACTIVE = "ACTIVE",
  CLOSED = "CLOSED",
  PENDING = "PENDING",
  REJECTED = "REJECTED",
}
