import { Router } from 'express';
import { getHome, getHealth } from '../controllers/home.controller';
import authRoutes from './auth.routes';
import contactRoutes from './contact.routes';
import productsRoutes from './products.routes';
import cartRoutes from './cart.routes';
import adminRoutes from './admin.routes';
import orderRoutes from './order.routes';
import couponRoutes from './coupon.routes';
import blogRoutes from './blog.routes';
import categoryRoutes from './category.routes';
import billRoutes from './bill.routes';
import settingsRoutes from './settings';
import dynamicRouteRoutes from './route.routes';
import accountingRoutes from './accounting.route';
import inventoryRoutes from './inventory.route';
import hubRoutes from './hub.route';
import quotationItemRoutes from './quotationItem.routes';
import quotationRoutes from './quotation.routes';
import scheduledEmailRoutes from './scheduledEmail.routes';
import purchaseRecordRoutes from './purchaseRecord.routes';
import crmContactRoutes from './crmContact.routes';
import deliveryRoutes from './delivery.routes';

const router = Router();

router.get('/', getHome);
router.get('/health', getHealth);
router.use('/auth', authRoutes);
router.use('/contact', contactRoutes);
router.use('/products', productsRoutes);
router.use('/cart', cartRoutes);
router.use('/admin/scheduled-emails', scheduledEmailRoutes);
router.use('/scheduled-emails', scheduledEmailRoutes);
router.use('/admin', adminRoutes);
router.use('/orders', orderRoutes);
router.use('/coupons', couponRoutes);
router.use('/blogs', blogRoutes);
router.use('/categories', categoryRoutes);
router.use('/bills', billRoutes);
router.use('/settings', settingsRoutes);
router.use('/dynamic-routes', dynamicRouteRoutes);
router.use('/accounting', accountingRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/hubs', hubRoutes);
router.use('/quotation-items', quotationItemRoutes);
router.use('/quotation', quotationRoutes);
router.use('/purchases', purchaseRecordRoutes);
router.use('/inventory-records', purchaseRecordRoutes);
router.use('/contacts', crmContactRoutes);
router.use('/delivery', deliveryRoutes);
router.use('/pincode', deliveryRoutes);

export default router;
