import axios from 'axios';

export class EmailService {
    public static async sendExportNotification(adminEmail: string, employeeName: string, folder: string, fileCount: number) {
        const apiKey = process.env.BREVO_API_KEY;
        const senderEmail = process.env.BREVO_FROM_EMAIL || 'noreply@onedriveaudit.com';

        if (!apiKey) {
            console.warn('BREVO_API_KEY is not configured. Skipping email.');
            return;
        }

        const dateStr = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

        const htmlContent = `
        <div style="font-family: Arial, sans-serif; background-color: #f4f6f9; padding: 20px; border-radius: 8px;">
            <div style="background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
                <h2 style="color: #e11d48; margin-top: 0;">&#9888; Security Alert: CSV Data Export</h2>
                <p style="color: #333; font-size: 16px;">Hello Admin,</p>
                <p style="color: #333; font-size: 14px;">This is an automated alert generated by your OneDrive Audit Tool to inform you that an employee has exported report data.</p>
                
                <table style="width: 100%; margin-top: 20px; border-collapse: collapse;">
                    <tr style="background-color: #f8fafc; border-bottom: 1px solid #e2e8f0;">
                        <th style="padding: 10px; text-align: left; color: #64748b;">Staff Member</th>
                        <td style="padding: 10px; font-weight: bold; color: #0f172a;">${employeeName}</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #e2e8f0;">
                        <th style="padding: 10px; text-align: left; color: #64748b;">Drive Folder</th>
                        <td style="padding: 10px; font-weight: bold; color: #0f172a;">${folder}</td>
                    </tr>
                    <tr style="background-color: #f8fafc; border-bottom: 1px solid #e2e8f0;">
                        <th style="padding: 10px; text-align: left; color: #64748b;">Records Downloaded</th>
                        <td style="padding: 10px; font-weight: bold; color: #0f172a;">${fileCount} items</td>
                    </tr>
                    <tr style="border-bottom: 1px solid #e2e8f0;">
                        <th style="padding: 10px; text-align: left; color: #64748b;">Date & Time (IST)</th>
                        <td style="padding: 10px; font-weight: bold; color: #0f172a;">${dateStr}</td>
                    </tr>
                </table>
                
                <p style="color: #64748b; font-size: 12px; margin-top: 30px;">
                    This is an automated system security log. Please do not reply directly to this email. Maintain vigilance over your corporate drive access logs.
                </p>
            </div>
        </div>
        `;

        try {
            await axios.post(
                'https://api.brevo.com/v3/smtp/email',
                {
                    sender: { name: 'OneDrive Audit Alert', email: senderEmail },
                    to: [{ email: adminEmail }],
                    subject: `[Audit Alert] CSV Data Export by ${employeeName}`,
                    htmlContent: htmlContent
                },
                {
                    headers: {
                        'accept': 'application/json',
                        'api-key': apiKey,
                        'content-type': 'application/json'
                    }
                }
            );
            console.log(`[EmailService] Alert sent to ${adminEmail}`);
        } catch (error: any) {
            console.error('[EmailService] Failed to send email:', error.response?.data || error.message);
        }
    }
}
